spring.application.name=Backend
# Following is the code for database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/rcsystem # rc = recycling collection
spring.datasource.username=root
spring.datasource.password=unstopableastik
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Database configuration ends here